[package]
name = "engine-sdk"
version = "0.1.0"
authors = []
edition = "2021"
description = ""
documentation = ""
readme = false
homepage = ""
repository = ""
license = ""
publish = false
autobenches = false

[dependencies]
engine-types = { path = "../engine-types", default-features = false }
evm = { git = "https://github.com/rust-blockchain/evm.git", rev = "07ae4451bb1d8d1cc81e5e07685691e68220a7d2", default-features = false }
sha3 = { version = "0.9.1", default-features = false }
protobuf = "2.27.1"
rlp = { version = "0.5.0", default-features = false }

[features]
std = ["engine-types/std"]