[package]
name = "eth2_hashing"
version = "0.3.0"
authors = []
edition = "2021"
description = ""
documentation = ""
readme = false
homepage = ""
repository = ""
license = ""
publish = false
autobenches = false

[dependencies]
lazy_static = { version = "1.4.0", optional = true }
sha2 = { version = "0.9.3", default-features = false }

[dev-dependencies]
rustc-hex = "2.1.0"

[features]
default = ["zero_hash_cache"]
zero_hash_cache = ["lazy_static"]