[package]
name = "engine-precompiles"
version = "0.1.0"
authors = []
edition = "2021"
description = ""
documentation = ""
readme = false
homepage = ""
repository = ""
license = ""
publish = false
autobenches = false

[dependencies]
engine-types = { path = "../engine-types", default-features = false }
engine-sdk = { path = "../engine-sdk", default-features = false }
bn-plus = { version = "0.4", default-features = false }
evm = { git = "https://github.com/rust-blockchain/evm.git", rev = "07ae4451bb1d8d1cc81e5e07685691e68220a7d2", default-features = false }
hex = { version = "0.4", default-features = false, features = ["alloc"] }
libsecp256k1 = { version = "0.3.5", default-features = false }
tcash-blake2 = { git = "https://github.com/telosprotocol/tcash-blake2", rev = "1d48fe82da9c622ae3c4b07db4af7151458c611c", default-features = false }
num = { version = "0.4.0", default-features = false, features = ["alloc"] }
ripemd160 = { version = "0.9.1", default-features = false }
sha2 = { version = "0.9.3", default-features = false }
sha3 = { version = "0.9.1", default-features = false }
protobuf = "2.27.1"

[features]
std = ["engine-types/std", "engine-sdk/std", "evm/std", "libsecp256k1/std", "ripemd160/std", "sha2/std", "sha3/std", "tcash-blake2/std"]